version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    build: ./Producer
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq

  consumer:
    build: ./Consumer
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq